# Generated by Django 3.1.5 on 2021-01-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='decs',
            new_name='desc',
        ),
    ]
